In [1]:
from absenteeism_module import *

In [2]:
df = pd.read_csv("Absenteeism_new_data.csv")
df.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0

In [ ]:
model = absenteeism_model("model","scaler")
model.load_and_clean_data("Absenteeism_new_data.csv")
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day of Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,False,0.0,False,True,6,4,179,26,30,237.656,19,1,0,0,0.116517,0
1,True,0.0,False,False,6,0,361,52,28,237.656,27,0,1,4,0.873232,1
2,False,0.0,False,True,6,2,155,12,34,237.656,25,0,2,0,0.270807,0
3,False,0.0,False,True,6,4,179,22,40,237.656,22,1,2,0,0.191412,0
4,True,0.0,False,False,6,4,155,12,34,237.656,25,0,2,0,0.698393,1
5,True,0.0,False,False,6,0,225,26,28,237.656,24,0,1,2,0.727914,1
6,True,0.0,False,False,6,2,118,15,46,275.089,25,0,2,0,0.573945,1
7,False,0.0,False,True,6,2,179,26,30,275.089,19,1,0,0,0.128766,0
8,False,0.0,False,True,6,4,118,10,37,275.089,28,0,0,0,0.120919,0
9,True,0.0,False,False,6,2,118,10,37,275.089,28,0,0,0,0.518596,1
10,False,0.0,False,True,6,3,378,49,36,275.089,21,0,2,4,0.427686,0
11,False,0.0,True,False,6,3,118,13,50,275.089,31,0,1,0,0.620238,1
12,False,0.0,True,False,6,4,233,51,31,275.089,21,1,1,8,0.302752,0
13,False,0.0,False,True,6,4,179,26,30,275.089,19,1,0,0,0.116510,0
14,False,0.0,False,False,6,0,235,29,48,275.089,33,0,1,5,0.082607,0
15,False,0.0,False,False,6,3,268,11,33,275.089,25,1,0,0,0.155795,0
16,False,0.0,True,False,6,3,118,13,50,275.089,31,0,1,0,0.620238,1
17,True,0.0,False,False,6,3,179,26,30,275.089,19,1,0,0,0.493819,0
18,False,0.0,False,True,6,3,291,31,40,275.089,25,0,1,1,0.371520,0
19,True,0.0,False,False,7,0,179,26,30,275.089,19,1,0,0,0.548292,1
20,False,0.0,False,True,7,0,118,10,37,275.089,28,0,0,0,0.153389,0
21,False,0.0,False,True,7,3,233,51,31,275.089,21,1,1,8,0.048833,0
22,True,0.0,False,False,7,4,118,10,37,275.089,28,0,0,0,0.501984,1
23,True,0.0,False,False,7,2,118,10,37,275.089,28,0,0,0,0.530444,1
24,False,0.0,False,True,7,2,233,51,31,275.089,21,1,1,8,0.051550,0
25,False,0.0,False,True,7,2,235,20,43,264.604,38,0,1,0,0.515689,1
26,False,0.0,True,False,7,4,233,51,31,264.604,21,1,1,8,0.312878,0
27,True,0.0,False,False,7,0,228,14,58,264.604,22,0,2,1,0.674755,1
28,False,0.0,False,True,7,0,118,10,37,264.604,28,0,0,0,0.153392,0
29,True,0.0,False,False,7,1,228,14,58,264.604,22,0,2,1,0.662124,1
30,False,0.0,False,True,7,1,189,29,33,264.604,25,0,2,2,0.260220,0
31,False,0.0,False,True,7,2,118,10,37,264.604,28,0,0,0,0.139166,0
32,False,0.0,False,True,7,2,361,52,28,264.604,27,0,1,4,0.479793,0
33,False,0.0,False,True,7,2,225,26,28,264.604,24,0,1,2,0.263735,0
34,True,0.0,False,False,7,0,369,17,31,264.604,25,0,3,0,0.970583,1
35,True,0.0,False,False,7,1,289,36,33,264.604,30,0,2,1,0.915688,1
36,True,0.0,False,False,7,1,235,11,37,264.604,29,1,1,1,0.768398,1
37,False,0.0,False,False,7,1,118,14,40,271.219,34,0,1,8,0.018783,0
38,False,0.0,False,False,7,2,231,35,39,271.219,35,0,2,2,0.251324,0
39,False,0.0,False,False,7,4,179,45,53,271.219,25,0,1,1,0.058758,0

In [5]:
model.predicted_outputs().to_csv("Absenteeism_Predictions.csv", index=False)